# Generated by Django 4.2.27 on 2025-12-11 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_latitude', models.FloatField(help_text='Starting point latitude')),
                ('starting_longitude', models.FloatField(help_text='Starting point longitude')),
                ('destination_latitude', models.FloatField(help_text='Destination latitude')),
                ('destination_longitude', models.FloatField(help_text='Destination longitude')),
                ('route_geometry', models.TextField(blank=True, default='', help_text='Encoded polyline string from Google Directions API')),
                ('available_seats', models.PositiveIntegerField(default=1, help_text='Number of available seats', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_ride_requests_allowed', models.BooleanField(default=True, help_text='Whether new ride requests are allowed')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-date_added'],
            },
        ),
    ]
